version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: docker:stable
    working_directory: .

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Authenticate with DigitalOcean Container Registry
          # command: docker login -u "$DIGITALOCEAN_REGISTRY_TOKEN" --password-stdin $DIGITALOCEAN_REGISTRY_TOKEN
          command: echo $DIGITALOCEAN_REGISTRY_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

