version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    executor: node/default
    working_directory: ~/project
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: docker:stable
    working_directory: ~/project

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Authenticate with DigitalOcean Container Registry
          command: docker login -u "$DIGITALOCEAN_REGISTRY_TOKEN" -password-stdin $DIGITALOCEAN_REGISTRY_TOKEN $DIGITALOCEAN_REGISTRY

      - run:
          name: Build and push Docker image
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME .
            docker tag $CIRCLE_PROJECT_REPONAME $DIGITALOCEAN_REGISTRY/$CIRCLE_PROJECT_REPONAME
            docker push $DIGITALOCEAN_REGISTRY/$CIRCLE_PROJECT_REPONAME

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context:
            - swimhistory
          requires:
            - build
          filters:
            branches:
              only: master

